V4 endpoint update
mindee/mindee-api-nodejs pull request #181
Opened 2023-07-11 15:25 UTC by sebastianMindee

## Description

- :boom: Update `Endpoint` syntax & auto-implementation
- :boom: Update `parse()` syntax
- :boom: Update all product syntax
- :coffin: Remove InvoiceV3
- :coffin: Remove ReceiptV3
- :recycle: Changed OCR to match new syntax
- :sparkles: Add OCR line & word operations
- :recycle: Update ESlint rules to account for new formats
- :wastebasket: Removed most products & tests to accommodate for future auto-generation
- :sparkles: Added support for CropperV1 as an extra field
- :bug: Fix page tests that weren't behaving correctly
- :bug: Fix table display for receiptV4
- :recycle: Disabled most CLI features (but updated to fit newer syntax). Won't work as-is.

## Related Issue

## How Has This Been Tested

## Types of changes

- [x] Docs change / refactoring / dependency upgrade
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Requires a change to the official Guide documentation.

2023-07-26 13:06 UTC, ianardee requested changes
* add fr.idCard, including tests
* update test data files submodule

2023-07-26 13:06 UTC, ianardee commented on docs/code_samples/custom_v1.txt
> +  );
should be something like this:
```
// Initialize a custom endpoint for this product
customEndpoint = mindeeClient.createEndpoint(
  "my-account",
  "my-endpoint"
);

// Parse it
const apiResponse = mindeeClient
  .parse(
    mindee.product.CustomV1,
    customEndpoint,
    inputSource,
  );
```

2023-07-26 13:06 UTC, ianardee commented on .eslintrc
> +}
missing return at EOF

2023-07-26 13:06 UTC, ianardee commented on README.md
> +    "my-version" // 1 by default, but it is strongly recommended you provide it
Pass an endpoint object instead, this can be in a separate PR as discussed.

2023-07-26 13:06 UTC, ianardee commented on README.md
> +
Not sure this belongs in the readme.

Remove for now and we'll do the documentation in another PR.

2023-07-26 13:06 UTC, ianardee commented on src/client.ts
> +        );
This is not a warning, it's normal operation. Set to debug or remove.

2023-07-26 13:06 UTC, ianardee commented on tests/product/cropper/cropperV1.spec.ts
> +    // expect(doc.toString()).to.be.equals(docString.toString());
re-enable this

2023-07-26 13:06 UTC, ianardee commented on tests/product/cropper/cropperV1.spec.ts
> +    // which classes inherit from 'Prediction' otherwise.
If this is true, we need to rework the type system :scream:

2023-07-26 13:06 UTC, ianardee commented on tests/product/cropper/cropperV1.spec.ts
> +    // expect(page0.prediction.cropping.length).to.be.equals(2);
re-enable

2023-07-26 13:50 UTC, sebastianMindee commented on .eslintrc
> +}
I can sense some irony in there...

2023-07-26 14:03 UTC, sebastianMindee commented on docs/code_samples/custom_v1.txt
> +  );
Will update in next PR instead to prevent CI break on this one.

2023-07-27 10:00 UTC, ianardee requested changes

2023-07-27 10:00 UTC, ianardee commented on src/product/fr/idCard/idCardV1.ts
> +  pages: Page<IdCardV1Document>[] = [];
```suggestion
  pages: Page<IdCardV1Page>[] = [];
```

2023-07-27 10:00 UTC, ianardee commented on tests/product/invoice/invoiceV4.spec.ts
> +  page1String: "tests/data/invoice/response_v4/page1_to_string.txt",
remove

2023-07-27 12:13 UTC, sebastianMindee commented on tests/product/invoice/invoiceV4.spec.ts
> +  page1String: "tests/data/invoice/response_v4/page1_to_string.txt",
I assume that just goes for `page1String` (which indeed does not exist)

2023-07-27 12:29 UTC, ianardee approved these changes

2023-07-27 12:32 UTC, merged