Add new supplier field and customer fields in Invoice object
mindee/mindee-api-nodejs pull request #71
Opened 2022-02-25 12:43 UTC by YanisMindee

New fields :

- supplierAddress
- customerName
- customerAddress
- customerCompanyRegistration

2022-03-01 13:59 UTC, ianardee requested changes

2022-03-01 13:59 UTC, ianardee commented on tests/data/api/invoice/v2/invoice_all_na.json
> +              "supplier_address": {
Should be a new file in a v3 folder

2022-03-01 15:48 UTC, YanisMindee commented on tests/data/api/invoice/v2/invoice_all_na.json
> +              "supplier_address": {
done

2022-03-01 17:41 UTC, ianardee approved these changes

2022-03-08 14:55 UTC, fharper approved these changes
LGTM

2022-03-08 14:57 UTC, merged